import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';

const projectState = v.union(v.literal('active'), v.literal('archived'), v.literal('completed'));
const healthState = v.union(v.literal('active'), v.literal('slowing'), v.literal('stalled'), v.literal('dying'));

export default defineSchema({
  users: defineTable({
    clerkId: v.string(),
    timeZone: v.string(),
    onboardingStatus: v.union(v.literal('notStarted'), v.literal('inProgress'), v.literal('complete')),
    reminderTime: v.optional(v.string()),
    notificationsEnabled: v.optional(v.boolean()),
    theme: v.union(v.literal('dark'), v.literal('light')),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_clerk_id', ['clerkId']),
  projects: defineTable({
    ownerId: v.id('users'),
    name: v.string(),
    repositoryId: v.optional(v.string()),
    repositoryName: v.optional(v.string()),
    repositoryUrl: v.optional(v.string()),
    deadline: v.optional(v.string()),
    state: projectState,
    focus: v.boolean(),
    progress: v.number(),
    health: healthState,
    healthScore: v.number(),
    healthReasons: v.array(v.string()),
    lastActivityAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
    completedAt: v.optional(v.number()),
    archivedAt: v.optional(v.number()),
    finishPromptShownAt: v.optional(v.number()),
  }).index('by_owner', ['ownerId']).index('by_owner_and_state', ['ownerId', 'state']).index('by_owner_and_repository', ['ownerId', 'repositoryId']),
  healthEvents: defineTable({
    ownerId: v.id('users'), projectId: v.id('projects'), previous: healthState, current: healthState,
    score: v.number(), reasons: v.array(v.string()), evaluatedAt: v.number(),
  }).index('by_project', ['projectId']).index('by_owner', ['ownerId']),
  features: defineTable({
    ownerId: v.id('users'),
    projectId: v.id('projects'),
    title: v.string(),
    bucket: v.union(v.literal('v1'), v.literal('backlog')),
    weight: v.union(v.literal('small'), v.literal('medium'), v.literal('large')),
    state: v.union(v.literal('open'), v.literal('completed')),
    order: v.number(),
    completedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_project', ['projectId']).index('by_owner_and_project', ['ownerId', 'projectId']),
  checklistItems: defineTable({
    ownerId: v.id('users'),
    projectId: v.optional(v.id('projects')),
    featureId: v.optional(v.id('features')),
    title: v.string(),
    localDate: v.string(),
    state: v.union(v.literal('open'), v.literal('completed')),
    order: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_owner_and_date', ['ownerId', 'localDate']),
  githubConnections: defineTable({
    ownerId: v.id('users'),
    githubUserId: v.string(),
    encryptedToken: v.string(),
    state: v.union(v.literal('connected'), v.literal('reauthorizationRequired'), v.literal('disconnected')),
    scopes: v.array(v.string()),
    lastSyncAt: v.optional(v.number()),
    lastError: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_owner', ['ownerId']).index('by_owner_and_github_user', ['ownerId', 'githubUserId']),
  githubOAuthStates: defineTable({
    ownerId: v.id('users'),
    value: v.string(),
    expiresAt: v.number(),
  }).index('by_value', ['value']),
  repositories: defineTable({
    ownerId: v.id('users'),
    githubRepositoryId: v.string(),
    fullName: v.string(),
    url: v.string(),
    defaultBranch: v.string(),
    visibility: v.union(v.literal('public'), v.literal('private')),
    updatedAt: v.number(),
  }).index('by_owner', ['ownerId']).index('by_owner_and_github_id', ['ownerId', 'githubRepositoryId']),
  notifications: defineTable({
    ownerId: v.id('users'), projectId: v.optional(v.id('projects')),
    type: v.union(v.literal('finishLine'), v.literal('healthChanged'), v.literal('dailyNudge')),
    title: v.string(), body: v.string(), deepLink: v.optional(v.string()), dateKey: v.string(), readAt: v.optional(v.number()), createdAt: v.number(),
  }).index('by_owner', ['ownerId']).index('by_owner_and_date', ['ownerId', 'dateKey']).index('by_project', ['projectId']),
});
