import { useRouter } from 'expo-router';
import { useState } from 'react';
import { useMutation, useQuery } from 'convex/react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { api } from '../../convex/_generated/api';
import { FontFamily, Palette } from '@/constants/theme';

export default function AddProjectScreen() {
  const router = useRouter(); const createProject = useMutation(api.projects.create); const repositories = useQuery(api.github.listRepositories, {});
  const [name, setName] = useState(''); const [repositoryOpen, setRepositoryOpen] = useState(false); const [repositoryId, setRepositoryId] = useState<string | null>(null); const [deadline, setDeadline] = useState(''); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const selectedRepository = repositories?.find((repository) => repository._id === repositoryId);
  const save = async () => { if (!name.trim()) { setError('Enter a project name.'); return; } setSaving(true); setError(null); try { await createProject({ name, repositoryId: selectedRepository?.githubRepositoryId, repositoryName: selectedRepository?.fullName, repositoryUrl: selectedRepository?.url, deadline: deadline || undefined }); router.replace('/(app)/projects'); } catch (caughtError) { setError(caughtError instanceof Error ? caughtError.message : 'Unable to add project.'); } finally { setSaving(false); } };
  return <View style={styles.screen}><SafeAreaView style={styles.safe}><View style={styles.header}><Pressable accessibilityLabel="Go back" accessibilityRole="button" onPress={() => router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Add Project</Text><View /></View><View style={styles.content}><Text style={styles.label}>Project name</Text><TextInput accessibilityLabel="Project name" onChangeText={setName} placeholder="e.g. MyApp" placeholderTextColor="#8FB5E6" selectionColor={Palette.cyan} style={styles.input} value={name} />{error ? <Text style={styles.error}>{error}</Text> : null}<Text style={styles.label}>GitHub repository</Text><Pressable accessibilityRole="button" onPress={() => setRepositoryOpen((open) => !open)} style={styles.select}><Text numberOfLines={1} style={selectedRepository ? styles.selectedText : styles.placeholder}>{selectedRepository?.fullName || (repositories?.length ? 'Choose a repository' : 'Connect GitHub to select a repository')}</Text><Text style={styles.chevron}>⌄</Text></Pressable>{repositoryOpen && repositories?.map((repository) => <Pressable accessibilityRole="radio" accessibilityState={{ selected: repository._id === repositoryId }} key={repository._id} onPress={() => { setRepositoryId(repository._id); setRepositoryOpen(false); }} style={styles.repository}><Text style={styles.repositoryText}>{repository.fullName}</Text><Text style={styles.repositoryMeta}>{repository.visibility}</Text></Pressable>)}<Text style={styles.label}>Optional deadline</Text><TextInput accessibilityLabel="Optional deadline" onChangeText={setDeadline} placeholder="e.g. 2026-10-30" placeholderTextColor="#8FB5E6" selectionColor={Palette.cyan} style={styles.input} value={deadline} /><Pressable accessibilityRole="button" accessibilityState={{ disabled: saving }} disabled={saving} onPress={save} style={({ pressed }) => [styles.button, (pressed || saving) && styles.pressed]}><Text style={styles.buttonText}>{saving ? 'Adding…' : 'Add Project'}</Text></Pressable></View></SafeAreaView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#020914' }, safe: { flex: 1 }, header: { height: 70, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { color: '#FFF', fontFamily: FontFamily.regular, fontSize: 41 }, title: { color: '#F5F8FF', fontFamily: FontFamily.bold, fontSize: 20 }, content: { paddingHorizontal: 22, paddingTop: 15 }, label: { marginTop: 20, marginBottom: 8, color: '#CDE5FF', fontFamily: FontFamily.medium, fontSize: 13 }, input: { height: 55, paddingHorizontal: 15, borderRadius: 13, borderWidth: 1, borderColor: '#0872C9', color: '#F5F9FF', fontFamily: FontFamily.regular, fontSize: 14, backgroundColor: '#052347' }, select: { height: 55, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderRadius: 13, borderWidth: 1, borderColor: '#0872C9', backgroundColor: '#052347' }, placeholder: { flex: 1, color: '#8FB5E6', fontFamily: FontFamily.regular, fontSize: 13 }, selectedText: { flex: 1, color: '#F5F9FF', fontFamily: FontFamily.regular, fontSize: 13 }, chevron: { color: '#9FD0FC', fontSize: 18 }, repository: { minHeight: 43, paddingHorizontal: 14, paddingVertical: 7, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: StyleSheet.hairlineWidth, borderColor: '#1765A8', backgroundColor: '#062A54' }, repositoryText: { flex: 1, color: '#E7F4FF', fontFamily: FontFamily.medium, fontSize: 11 }, repositoryMeta: { color: '#75BFF0', fontFamily: FontFamily.regular, fontSize: 9 }, error: { marginTop: 8, color: '#FF9DA5', fontFamily: FontFamily.regular, fontSize: 12 }, button: { height: 54, marginTop: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 27, backgroundColor: '#087FFF', shadowColor: '#00CFF5', shadowOpacity: .38, shadowRadius: 14, elevation: 8 }, buttonText: { color: '#FFF', fontFamily: FontFamily.semibold, fontSize: 16 }, pressed: { opacity: .76 } });
