import { useRouter } from 'expo-router';
import { useState } from 'react';
import { useMutation } from 'convex/react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { api } from '../../convex/_generated/api';
import { FontFamily, Palette } from '@/constants/theme';

export default function AddProjectScreen() {
  const router = useRouter(); const createProject = useMutation(api.projects.create);
  const [name, setName] = useState(''); const [repositoryUrl, setRepositoryUrl] = useState(''); const [deadline, setDeadline] = useState(''); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const save = async () => { if (!name.trim()) { setError('Enter a project name.'); return; } setSaving(true); setError(null); try { await createProject({ name, repositoryUrl: repositoryUrl || undefined, deadline: deadline || undefined }); router.replace('/(app)/projects'); } catch (caughtError) { setError(caughtError instanceof Error ? caughtError.message : 'Unable to add project.'); } finally { setSaving(false); } };
  return <View style={styles.screen}><SafeAreaView style={styles.safe}><View style={styles.header}><Pressable accessibilityLabel="Go back" accessibilityRole="button" onPress={() => router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Add Project</Text><View /></View><View style={styles.content}><Text style={styles.label}>Project name</Text><TextInput accessibilityLabel="Project name" onChangeText={setName} placeholder="e.g. MyApp" placeholderTextColor="#8FB5E6" selectionColor={Palette.cyan} style={styles.input} value={name} />{error ? <Text style={styles.error}>{error}</Text> : null}<Text style={styles.label}>GitHub repository URL</Text><TextInput accessibilityLabel="GitHub repository URL" autoCapitalize="none" onChangeText={setRepositoryUrl} placeholder="Optional — connect GitHub later" placeholderTextColor="#8FB5E6" selectionColor={Palette.cyan} style={styles.input} value={repositoryUrl} /><Text style={styles.label}>Optional deadline</Text><TextInput accessibilityLabel="Optional deadline" onChangeText={setDeadline} placeholder="e.g. 2026-10-30" placeholderTextColor="#8FB5E6" selectionColor={Palette.cyan} style={styles.input} value={deadline} /><Pressable accessibilityRole="button" accessibilityState={{ disabled: saving }} disabled={saving} onPress={save} style={({ pressed }) => [styles.button, (pressed || saving) && styles.pressed]}><Text style={styles.buttonText}>{saving ? 'Adding…' : 'Add Project'}</Text></Pressable></View></SafeAreaView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#020914' }, safe: { flex: 1 }, header: { height: 70, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { color: '#FFF', fontFamily: FontFamily.regular, fontSize: 41 }, title: { color: '#F5F8FF', fontFamily: FontFamily.bold, fontSize: 20 }, content: { paddingHorizontal: 22, paddingTop: 15 }, label: { marginTop: 20, marginBottom: 8, color: '#CDE5FF', fontFamily: FontFamily.medium, fontSize: 13 }, input: { height: 55, paddingHorizontal: 15, borderRadius: 13, borderWidth: 1, borderColor: '#0872C9', color: '#F5F9FF', fontFamily: FontFamily.regular, fontSize: 14, backgroundColor: '#052347' }, error: { marginTop: 8, color: '#FF9DA5', fontFamily: FontFamily.regular, fontSize: 12 }, button: { height: 54, marginTop: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 27, backgroundColor: '#087FFF', shadowColor: '#00CFF5', shadowOpacity: .38, shadowRadius: 14, elevation: 8 }, buttonText: { color: '#FFF', fontFamily: FontFamily.semibold, fontSize: 16 }, pressed: { opacity: .76 } });
