import { useLocalSearchParams, useRouter } from 'expo-router';
import { useState } from 'react';
import { useMutation, useQuery } from 'convex/react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { api } from '../../convex/_generated/api';
import { FontFamily, Palette } from '@/constants/theme';

const weights = ['small', 'medium', 'large'] as const;
const buckets = ['v1', 'backlog'] as const;
export default function EditFeatureScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>();
  const feature = useQuery(api.features.get, id ? { featureId: id as never } : 'skip');
  const update = useMutation(api.features.update); const remove = useMutation(api.features.remove);
  const [title, setTitle] = useState<string>(); const [weight, setWeight] = useState<typeof weights[number]>(); const [bucket, setBucket] = useState<typeof buckets[number]>(); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  if (feature === undefined) return <View style={styles.screen}><Text style={styles.loading}>Loading feature…</Text></View>;
  if (!feature) return <View style={styles.screen}><Text style={styles.loading}>Feature not found.</Text></View>;
  const currentTitle = title ?? feature.title; const currentWeight = weight ?? feature.weight; const currentBucket = bucket ?? feature.bucket;
  const save = async () => { if (!currentTitle.trim()) { setError('Enter a feature title.'); return; } setSaving(true); setError(null); try { await update({ featureId: feature._id, title: currentTitle, weight: currentWeight, bucket: currentBucket }); router.back(); } catch (caughtError) { setError(caughtError instanceof Error ? caughtError.message : 'Unable to save feature.'); } finally { setSaving(false); } };
  const deleteFeature = () => Alert.alert('Delete feature?', currentTitle, [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { await remove({ featureId: feature._id }); router.back(); } }]);
  return <View style={styles.screen}><SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Edit Feature</Text><View /></View><View style={styles.content}><Text style={styles.label}>Feature title</Text><TextInput accessibilityLabel="Feature title" onChangeText={setTitle} style={styles.input} value={currentTitle} /><Text style={styles.label}>Weight</Text><View style={styles.options}>{weights.map((item) => <Pressable accessibilityRole="radio" accessibilityState={{ selected: currentWeight === item }} key={item} onPress={() => setWeight(item)} style={[styles.option, currentWeight === item && styles.optionSelected]}><Text style={[styles.optionText, currentWeight === item && styles.optionTextSelected]}>{item}</Text><Text style={styles.optionMeta}>{item === 'small' ? '15 min' : item === 'medium' ? '30 min' : '60 min'}</Text></Pressable>)}</View><Text style={styles.label}>Bucket</Text><View style={styles.options}>{buckets.map((item) => <Pressable accessibilityRole="radio" accessibilityState={{ selected: currentBucket === item }} key={item} onPress={() => setBucket(item)} style={[styles.option, currentBucket === item && styles.optionSelected]}><Text style={[styles.optionText, currentBucket === item && styles.optionTextSelected]}>{item === 'v1' ? 'v1 delivery' : 'Backlog'}</Text></Pressable>)}</View>{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable disabled={saving} onPress={() => void save()} style={styles.button}><Text style={styles.buttonText}>{saving ? 'Saving…' : 'Save changes'}</Text></Pressable><Pressable onPress={deleteFeature} style={styles.delete}><Text style={styles.deleteText}>Delete feature</Text></Pressable></View></SafeAreaView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#020914' }, safe: { flex: 1 }, header: { height: 70, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { color: '#FFF', fontSize: 41 }, title: { color: '#F5F8FF', fontFamily: FontFamily.bold, fontSize: 20 }, content: { padding: 22 }, label: { marginTop: 18, marginBottom: 8, color: '#CDE5FF', fontFamily: FontFamily.medium, fontSize: 13 }, input: { height: 55, paddingHorizontal: 15, borderRadius: 13, borderWidth: 1, borderColor: '#0872C9', color: '#F5F9FF', fontSize: 14, backgroundColor: '#052347' }, options: { flexDirection: 'row', gap: 7 }, option: { flex: 1, minHeight: 48, padding: 8, justifyContent: 'center', borderRadius: 9, borderWidth: 1, borderColor: '#14568B', backgroundColor: '#06274F' }, optionSelected: { borderColor: Palette.cyan, backgroundColor: '#073B6C' }, optionText: { color: '#A8C9EC', fontFamily: FontFamily.medium, fontSize: 11, textAlign: 'center' }, optionTextSelected: { color: '#FFF' }, optionMeta: { marginTop: 3, color: '#79AADD', fontFamily: FontFamily.regular, fontSize: 8, textAlign: 'center' }, error: { marginTop: 10, color: '#FF9DA5', fontSize: 12 }, button: { height: 54, marginTop: 28, alignItems: 'center', justifyContent: 'center', borderRadius: 27, backgroundColor: '#087FFF' }, buttonText: { color: '#FFF', fontFamily: FontFamily.semibold, fontSize: 16 }, delete: { alignItems: 'center', padding: 17 }, deleteText: { color: '#FF929D', fontFamily: FontFamily.medium, fontSize: 12 }, loading: { margin: 22, color: '#A9CEEE' },
});
