import FontAwesome from '@expo/vector-icons/FontAwesome';
import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { FontFamily, Palette } from '@/constants/theme';

export default function EmptyStatesScreen() {
  const router = useRouter();
  return <View style={styles.screen}><SafeAreaView style={styles.safe}><View style={styles.header}><Pressable accessibilityLabel="Back" accessibilityRole="button" onPress={() => router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Empty States</Text><View /></View><View style={styles.content}><EmptyCard icon="rocket" title="No projects yet!" copy="Start by creating your first project and bring your ideas to life." action="Create Project" onPress={() => router.push('/add-project')} /><EmptyCard icon="check" title="Graveyard cleaned." copy="You’re all set! Nothing to show." action="View Tasks" onPress={() => router.replace('/(app)/home')} /></View><Text style={styles.build}>Build 1.0.0 · Productivity · Better Tomorrow</Text></SafeAreaView></View>;
}
function EmptyCard({ action, copy, icon, onPress, title }: { action: string; copy: string; icon: 'rocket' | 'check'; onPress: () => void; title: string }) { return <View style={styles.card}><View style={styles.art}><View style={styles.artCircle}><FontAwesome color={Palette.cyan} name={icon} size={icon === 'rocket' ? 42 : 38} /></View><View style={[styles.star, styles.starOne]} /><View style={[styles.star, styles.starTwo]} /><View style={[styles.star, styles.starThree]} /></View><Text style={styles.cardTitle}>{title}</Text><Text style={styles.copy}>{copy}</Text><Pressable accessibilityRole="button" onPress={onPress} style={styles.button}><Text style={styles.buttonText}>+ {action}</Text></Pressable></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#020914' }, safe: { flex: 1 }, header: { height: 62, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { color: '#E9F6FF', fontFamily: FontFamily.regular, fontSize: 38 }, title: { color: '#F3F8FF', fontFamily: FontFamily.bold, fontSize: 17 }, content: { paddingHorizontal: 17, gap: 14 }, card: { minHeight: 263, paddingHorizontal: 22, paddingVertical: 20, alignItems: 'center', borderRadius: 10, borderWidth: 1, borderColor: '#0876C8', backgroundColor: '#06294F' }, art: { width: 138, height: 111, alignItems: 'center', justifyContent: 'center' }, artCircle: { width: 82, height: 82, borderRadius: 41, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#00CFF5', backgroundColor: '#063A6E', shadowColor: '#00D6FF', shadowOpacity: .65, shadowRadius: 18, elevation: 9 }, star: { position: 'absolute', width: 6, height: 6, borderRadius: 3, backgroundColor: '#00D6FF' }, starOne: { top: 12, left: 18 }, starTwo: { right: 11, top: 26, backgroundColor: '#FFDD25' }, starThree: { left: 25, bottom: 9, backgroundColor: '#9255FF' }, cardTitle: { marginTop: 7, color: '#F2F8FF', fontFamily: FontFamily.bold, fontSize: 17 }, copy: { marginTop: 8, color: '#A9CFF3', textAlign: 'center', fontFamily: FontFamily.regular, fontSize: 11, lineHeight: 16 }, button: { alignSelf: 'stretch', height: 36, marginTop: 16, alignItems: 'center', justifyContent: 'center', borderRadius: 19, backgroundColor: '#087FFF', shadowColor: '#00CFF5', shadowOpacity: .38, shadowRadius: 9, elevation: 6 }, buttonText: { color: '#FFF', fontFamily: FontFamily.semibold, fontSize: 12 }, build: { marginTop: 'auto', marginBottom: 13, color: '#6698C8', textAlign: 'center', fontFamily: FontFamily.regular, fontSize: 8 } });
