import FontAwesome from '@expo/vector-icons/FontAwesome';
import { LinearGradient } from 'expo-linear-gradient';
import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { FontFamily, Palette } from '@/constants/theme';

export default function ForgotPasswordScreen() {
  const router = useRouter();
  return <View style={styles.screen}><LinearGradient colors={['#031A36', '#030E20', '#020914']} end={{ x: .72, y: 1 }} start={{ x: .1, y: 0 }} style={StyleSheet.absoluteFill} /><SafeAreaView style={styles.safe}><Pressable accessibilityLabel="Back to sign in" accessibilityRole="button" hitSlop={12} onPress={() => router.back()} style={styles.back}><Text style={styles.backIcon}>‹</Text></Pressable><View style={styles.content}><View style={styles.icon}><FontAwesome color={Palette.cyan} name="lock" size={31} /></View><Text style={styles.title}>Reset your <Text style={styles.accent}>password</Text></Text><Text style={styles.subtitle}>Enter your email and we’ll send you a secure link to reset your password.</Text><View style={styles.field}><FontAwesome color="#B7D7FF" name="envelope-o" size={20} /><View style={styles.copy}><Text style={styles.label}>Email Address</Text><TextInput accessibilityLabel="Email address" autoCapitalize="none" autoComplete="email" keyboardType="email-address" placeholder="you@example.com" placeholderTextColor="#8FB5E6" selectionColor={Palette.cyan} style={styles.input} textContentType="emailAddress" /></View></View><Pressable accessibilityRole="button" style={({ pressed }) => [styles.button, pressed && styles.pressed]}><LinearGradient colors={['#0878FF', '#0068FF', '#00D5F5']} end={{ x: 1, y: .5 }} start={{ x: 0, y: .5 }} style={styles.gradient}><Text style={styles.buttonText}>Send Reset Link</Text><Text style={styles.arrow}>→</Text></LinearGradient></Pressable><Pressable accessibilityRole="button" onPress={() => router.replace('/sign-in')}><Text style={styles.return}>Back to <Text style={styles.link}>Sign In</Text></Text></Pressable></View></SafeAreaView></View>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#020914' }, safe: { flex: 1 }, back: { paddingLeft: 28, paddingTop: 10 }, backIcon: { color: '#F2F8FF', fontFamily: FontFamily.regular, fontSize: 44, lineHeight: 36 }, content: { flex: 1, paddingHorizontal: 28, paddingTop: 86 }, icon: { width: 74, height: 74, borderRadius: 24, borderWidth: 1, borderColor: '#007BDC', backgroundColor: 'rgba(3, 40, 86, .7)', alignItems: 'center', justifyContent: 'center', shadowColor: '#00CFFF', shadowOpacity: .36, shadowRadius: 15, elevation: 7 }, title: { marginTop: 29, color: '#F7FAFF', fontFamily: FontFamily.extraBold, fontSize: 34, lineHeight: 42, letterSpacing: -1.2 }, accent: { color: Palette.cyan }, subtitle: { marginTop: 10, color: '#B1D2FF', fontFamily: FontFamily.regular, fontSize: 16, lineHeight: 23 }, field: { height: 72, marginTop: 32, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 16, borderWidth: 1, borderColor: '#007BDC', backgroundColor: 'rgba(3, 40, 86, .58)' }, copy: { flex: 1 }, label: { color: '#B8D8FF', fontFamily: FontFamily.regular, fontSize: 13 }, input: { height: 31, padding: 0, color: '#EFF7FF', fontFamily: FontFamily.regular, fontSize: 16 }, button: { marginTop: 24, borderRadius: 27, shadowColor: '#00BBFF', shadowOpacity: .48, shadowRadius: 15, shadowOffset: { width: 0, height: 7 }, elevation: 8 }, gradient: { height: 54, borderRadius: 27, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 20 }, buttonText: { color: '#FFF', fontFamily: FontFamily.semibold, fontSize: 17 }, arrow: { color: '#FFF', fontSize: 28 }, return: { marginTop: 28, textAlign: 'center', color: '#A9C9F3', fontFamily: FontFamily.regular, fontSize: 14 }, link: { color: '#00BDFF', fontFamily: FontFamily.semibold }, pressed: { opacity: .78, transform: [{ scale: .99 }] } });
