import FontAwesome from '@expo/vector-icons/FontAwesome';
import { type ReactNode } from 'react';
import { useRouter } from 'expo-router';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';

import { BottomTabInset, FontFamily, Palette } from '@/constants/theme';

export function AppShell({ children, title, action, showBack = false }: { children: ReactNode; title?: string; action?: ReactNode; showBack?: boolean }) {
  const router = useRouter();
  return <View style={styles.screen}><SafeAreaView style={styles.safe}><View style={styles.header}>{showBack ? <Pressable accessibilityLabel="Go back" accessibilityRole="button" hitSlop={10} onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable> : null}{title ? <Text numberOfLines={1} style={[styles.title, showBack && styles.titleWithBack]}>{title}</Text> : <View style={styles.brandBlock}><Text style={styles.brand}>Dev<Text style={styles.accent}>Task</Text></Text><Text style={styles.tagline}>BUILD. FINISH. GROW.</Text></View>}{action ? <View style={styles.action}>{action}</View> : null}</View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>{children}</ScrollView></SafeAreaView></View>;
}
export function SectionTitle({ children, action }: { children: string; action?: ReactNode }) { return <View style={styles.sectionTitle}><Text style={styles.sectionText}>{children}</Text>{action}</View>; }
export function ProjectCard({ name, progress, health, onPress }: { name: string; progress: number; health: string; onPress?: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.ring}><Text style={styles.ringText}>{progress}%</Text></View><View style={styles.cardCopy}><Text style={styles.cardName}>{name}</Text><Text style={styles.cardMeta}>{health} · Updated today</Text><View style={styles.track}><View style={[styles.fill, { width: `${progress}%` }]} /></View></View><FontAwesome color="#82BFFF" name="chevron-right" size={13} /></Pressable>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#020914' }, safe: { flex: 1 }, header: { minHeight: 72, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', gap: 8 }, back: { width: 32, height: 42, alignItems: 'flex-start', justifyContent: 'center' }, backText: { color: '#E8F5FF', fontFamily: FontFamily.regular, fontSize: 36, lineHeight: 38 }, title: { flex: 1, color: '#F5F8FF', fontFamily: FontFamily.bold, fontSize: 26 }, titleWithBack: { fontSize: 20 }, brandBlock: { flex: 1 }, brand: { color: '#F5F8FF', fontFamily: FontFamily.extraBold, fontSize: 23 }, accent: { color: Palette.cyan }, tagline: { marginTop: 2, color: '#6198D3', fontFamily: FontFamily.medium, fontSize: 9, letterSpacing: 1.4 }, action: { marginLeft: 'auto', minWidth: 40, minHeight: 40, alignItems: 'center', justifyContent: 'center' }, content: { paddingHorizontal: 20, paddingBottom: 24 + BottomTabInset }, sectionTitle: { marginTop: 25, marginBottom: 11, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, sectionText: { color: '#F2F7FF', fontFamily: FontFamily.semibold, fontSize: 17 }, card: { minHeight: 80, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 1, borderColor: '#0765B7', borderRadius: 15, backgroundColor: 'rgba(4, 34, 73, .7)', marginBottom: 10 }, ring: { width: 45, height: 45, borderRadius: 23, borderWidth: 4, borderColor: '#00CFF5', alignItems: 'center', justifyContent: 'center' }, ringText: { color: '#DFF5FF', fontFamily: FontFamily.mono, fontSize: 10 }, cardCopy: { flex: 1 }, cardName: { color: '#F4F8FF', fontFamily: FontFamily.semibold, fontSize: 15 }, cardMeta: { marginTop: 3, color: '#8FB5E6', fontFamily: FontFamily.regular, fontSize: 11 }, track: { height: 4, overflow: 'hidden', borderRadius: 5, backgroundColor: '#143A66', marginTop: 9 }, fill: { height: '100%', borderRadius: 5, backgroundColor: '#00CFF5' }, pressed: { opacity: .75, transform: [{ scale: .99 }] } });
